export interface PostSpec {
  slug: string
  title: string
  description: string
  category: string
  tags: string[]
  seoKeyword: string
  searchVolume: number
  tier: 1 | 2 | 3
  publishWeek: number
  featured?: boolean
  relatedCalculator?: string
  imagePrompt: string
  publishedAt: string
}

export const POSTS: PostSpec[] = [
  // ═══════════════════════════════════════
  // TIER 1 — Weeks 1-3 (low competition)
  // ═══════════════════════════════════════
  {
    slug: 'reduce-emi-or-tenure-after-part-payment',
    title: 'Reduce EMI or Reduce Tenure After Part Payment — The Verdict With Real Numbers',
    description: 'When your bank asks whether to reduce EMI or tenure after a part payment, most borrowers guess. We run the exact numbers on a ₹50L loan so you never have to guess again.',
    category: 'Part Payments',
    tags: ['part payment', 'EMI', 'tenure', 'home loan', 'reduce EMI', 'reduce tenure'],
    seoKeyword: 'reduce EMI or tenure after part payment',
    searchVolume: 4000,
    tier: 1,
    publishWeek: 1,
    featured: true,
    relatedCalculator: '/',
    imagePrompt: 'Split illustration showing two paths from a single loan payment — one path shows lower monthly payment label, other shows a shorter timeline label, clean financial infographic, blue and orange, no text, vector style, professional fintech aesthetic',
    publishedAt: '2025-04-01',
  },
  {
    slug: 'part-payment-year-3-vs-year-10',
    title: 'Part Payment in Year 3 vs Year 10: When Does It Save the Most Interest?',
    description: 'A ₹5L part payment in year 3 and a ₹5L part payment in year 10 do not save the same interest. The difference is shocking. Here is the exact calculation.',
    category: 'Part Payments',
    tags: ['part payment', 'timing', 'interest saved', 'home loan', 'prepayment strategy'],
    seoKeyword: 'home loan part payment timing interest saved',
    searchVolume: 1200,
    tier: 1,
    publishWeek: 1,
    relatedCalculator: '/',
    imagePrompt: 'Timeline illustration showing a 20-year home loan bar with two marked points — year 3 and year 10 — each with a rupee savings indicator, the year 3 indicator significantly larger, clean infographic style, no text, blue and green palette',
    publishedAt: '2025-04-02',
  },
  {
    slug: 'how-much-interest-does-10-lakh-part-payment-save',
    title: 'How Much Interest Does a ₹10 Lakh Part Payment Actually Save on Your Home Loan?',
    description: 'Most borrowers make a part payment hoping it will save "a lot." We calculate the exact rupee savings for a ₹10L part payment at different stages of a ₹50L home loan.',
    category: 'Part Payments',
    tags: ['part payment', '10 lakh', 'interest saved', 'home loan', 'prepayment'],
    seoKeyword: 'how much interest saved part payment 10 lakh home loan',
    searchVolume: 800,
    tier: 1,
    publishWeek: 1,
    relatedCalculator: '/',
    imagePrompt: 'Minimalist illustration of a piggy bank with a rupee sign being fed by a large payment arrow, with a shrinking loan balance visual, professional financial graphic, teal and white, no text, clean vector',
    publishedAt: '2025-04-03',
  },
  {
    slug: 'pre-emi-vs-full-emi-under-construction',
    title: 'Pre-EMI vs Full EMI for Under-Construction Property: Which Costs Less?',
    description: 'Your builder is asking you to choose Pre-EMI or Full EMI before you even have the keys. Making the wrong choice can cost you ₹3-8 lakhs extra. Here is the honest comparison.',
    category: 'Home Loans',
    tags: ['pre-EMI', 'full EMI', 'under construction', 'home loan', 'builder'],
    seoKeyword: 'pre EMI vs full EMI under construction flat India',
    searchVolume: 7000,
    tier: 1,
    publishWeek: 2,
    relatedCalculator: '/',
    imagePrompt: 'Illustration of a building under construction transitioning to a completed home, with two payment timeline bars below it showing different structures, professional real estate financial style, blue and orange, no text, no faces, vector',
    publishedAt: '2025-04-07',
  },
  {
    slug: 'credit-card-minimum-due-trap',
    title: 'Paying Only Minimum Due on Your Credit Card? Here Is What It Actually Costs',
    description: 'The minimum due feels manageable. The real cost is a trap. We show exactly how long it takes to clear a ₹30,000 credit card balance at minimum payments — and the total interest paid.',
    category: 'Credit Cards',
    tags: ['credit card', 'minimum due', 'debt trap', 'interest', 'credit card debt'],
    seoKeyword: 'credit card minimum due trap interest cost India',
    searchVolume: 8000,
    tier: 1,
    publishWeek: 2,
    relatedCalculator: '/',
    imagePrompt: 'Minimalist illustration of a credit card with a growing debt spiral behind it, warning concept without being alarming, red and white, clean vector style, no text, no faces, professional fintech aesthetic',
    publishedAt: '2025-04-08',
  },
  {
    slug: 'how-to-read-home-loan-statement',
    title: 'How to Read Your Home Loan Amortization Statement (What Your Bank Does Not Explain)',
    description: 'Your home loan statement has numbers that directly affect your net worth. Most borrowers scan and file it. We show you exactly what every column means and what to act on.',
    category: 'Home Loans',
    tags: ['home loan statement', 'amortization', 'bank statement', 'loan tracking'],
    seoKeyword: 'how to read home loan statement India',
    searchVolume: 5000,
    tier: 1,
    publishWeek: 2,
    relatedCalculator: '/',
    imagePrompt: 'Illustration of a financial document with a magnifying glass highlighting key rows, educational infographic feel, simplified bank statement aesthetic, teal and white, no actual numbers visible, no text outside metaphor, professional',
    publishedAt: '2025-04-09',
  },
  {
    slug: 'education-loan-section-80e-no-upper-limit',
    title: 'Education Loan Section 80E: The Tax Deduction With No Upper Limit',
    description: "Section 80E lets you deduct 100% of education loan interest with absolutely no cap. There is no ceiling. Yet most borrowers never claim it. Here is exactly how it works.",
    category: 'Tax Planning',
    tags: ['education loan', '80E', 'tax deduction', 'income tax', 'no upper limit'],
    seoKeyword: 'education loan 80E deduction no upper limit India',
    searchVolume: 6500,
    tier: 1,
    publishWeek: 3,
    relatedCalculator: '/calculators/tax-benefit',
    imagePrompt: 'Clean illustration of graduation cap with an upward infinity arrow and rupee symbol, tax saving concept, educational theme, blue and gold, no text, no faces, vector style',
    publishedAt: '2025-04-14',
  },
  {
    slug: 'home-loan-balance-transfer-break-even-calculator',
    title: 'Home Loan Balance Transfer: The Break-Even Calculator You Must Use Before Switching',
    description: 'A 0.5% lower rate sounds great. But after processing fees and legal charges, when do you actually start saving? Most borrowers never calculate this. We do it for you.',
    category: 'Home Loans',
    tags: ['balance transfer', 'home loan', 'break even', 'refinance', 'interest rate'],
    seoKeyword: 'home loan balance transfer break even months India',
    searchVolume: 9000,
    tier: 1,
    publishWeek: 3,
    relatedCalculator: '/calculators/balance-transfer',
    imagePrompt: 'Clean professional illustration showing a transfer arrow between two banks with a timeline axis showing break-even point marked, cost vs savings concept, teal and white, no text, vector art',
    publishedAt: '2025-04-15',
  },
  {
    slug: 'rbi-zero-prepayment-penalty-floating-rate',
    title: 'RBI Rule: Your Floating Rate Home Loan Has Zero Prepayment Penalty — Always',
    description: 'Most home loan borrowers do not know this. By RBI mandate, banks cannot charge any prepayment penalty on floating rate home loans. Here is the rule, what it means for you, and how to use it.',
    category: 'Home Loans',
    tags: ['RBI', 'prepayment penalty', 'floating rate', 'home loan', 'regulation'],
    seoKeyword: 'RBI prepayment penalty floating rate home loan rule India',
    searchVolume: 1500,
    tier: 1,
    publishWeek: 3,
    relatedCalculator: '/',
    imagePrompt: 'Illustration of Reserve Bank of India building silhouette with a green checkmark and zero symbol, regulatory clarity concept, saffron and blue tones of Indian flag, no text, clean professional vector',
    publishedAt: '2025-04-16',
  },

  // ═══════════════════════════════════════
  // TIER 2 — Weeks 4-8 (medium competition)
  // ═══════════════════════════════════════
  {
    slug: 'sip-vs-home-loan-prepayment',
    title: 'SIP vs Home Loan Prepayment: The Honest Answer for Indian Borrowers',
    description: 'Should you invest surplus in SIP or prepay your home loan? The answer depends on your tax bracket and where you are in your loan. We show the math honestly, including when SIP loses.',
    category: 'Debt Strategy',
    tags: ['SIP', 'prepayment', 'mutual fund', 'home loan', 'investment', 'comparison'],
    seoKeyword: 'sip vs home loan prepayment India',
    searchVolume: 18000,
    tier: 2,
    publishWeek: 4,
    featured: true,
    relatedCalculator: '/calculators/sip-vs-prepayment',
    imagePrompt: 'Split illustration showing two financial paths — one side a growing SIP investment chart, other side a shrinking loan balance chart, clean comparison visual, green and blue, no text, professional fintech',
    publishedAt: '2025-04-21',
  },
  {
    slug: 'debt-snowball-vs-avalanche-india',
    title: 'Debt Snowball vs Debt Avalanche: Which Payoff Strategy Works for Indian Loans?',
    description: 'You have a home loan, car loan, and personal loan. Do you pay the smallest first (snowball) or the highest rate first (avalanche)? The math says avalanche. But psychology says something else.',
    category: 'Debt Strategy',
    tags: ['debt snowball', 'debt avalanche', 'payoff strategy', 'multiple loans'],
    seoKeyword: 'debt snowball vs avalanche India multiple loans',
    searchVolume: 3000,
    tier: 2,
    publishWeek: 4,
    relatedCalculator: '/dashboard/planner',
    imagePrompt: 'Split comparison showing two strategies — snowball as small debts being cleared first in sequence, avalanche as highest-interest debt attacked first, clean financial strategy infographic, blue and white, no text, vector',
    publishedAt: '2025-04-22',
  },
  {
    slug: 'gold-loan-vs-personal-loan-india',
    title: 'Gold Loan vs Personal Loan: Which Is Actually Cheaper for ₹5 Lakh?',
    description: 'Gold loans have lower rates but your jewellery is at risk. Personal loans have no collateral risk but higher rates. We compare both with real numbers for ₹5L over 12 months.',
    category: 'Personal Loans',
    tags: ['gold loan', 'personal loan', 'interest rate', 'collateral', 'comparison'],
    seoKeyword: 'gold loan vs personal loan interest rate India',
    searchVolume: 11000,
    tier: 2,
    publishWeek: 4,
    relatedCalculator: '/',
    imagePrompt: 'Split comparison of gold jewellery on one side and a personal loan document on the other, balanced scale or comparison visual, warm gold and cool blue palette, no text, no faces, professional financial infographic',
    publishedAt: '2025-04-23',
  },
  {
    slug: 'rbi-rate-cut-emi-impact',
    title: 'RBI Cut the Repo Rate — Should Your Home Loan EMI Have Dropped?',
    description: 'When RBI cuts rates, your floating rate home loan EMI should fall. But many banks delay passing on the benefit. Here is what to check, how to calculate the expected drop, and what to do if it has not happened.',
    category: 'EMI Management',
    tags: ['RBI', 'repo rate', 'EMI', 'floating rate', 'RLLR', 'rate cut'],
    seoKeyword: 'RBI rate cut EMI impact floating home loan 2025',
    searchVolume: 12000,
    tier: 2,
    publishWeek: 5,
    relatedCalculator: '/rbi-rates',
    imagePrompt: 'Infographic showing a rate-cut arrow flowing from a central bank building to a home loan EMI payment that decreases, clean financial news illustration style, saffron and blue Indian tones, no text, vector',
    publishedAt: '2025-04-28',
  },
  {
    slug: 'pmay-subsidy-eligibility-2025',
    title: 'PMAY Subsidy 2025: Are You Eligible for ₹2.67 Lakh? The Complete Guide',
    description: "The Pradhan Mantri Awas Yojana subsidy can cut your home loan cost by up to ₹2.67 lakh. Most eligible borrowers never claim it. Here is the exact eligibility criteria, how to apply, and what the subsidy actually does to your EMI.",
    category: 'Home Loans',
    tags: ['PMAY', 'subsidy', 'first time buyer', 'government scheme', 'home loan'],
    seoKeyword: 'PMAY subsidy eligibility 2025 India how to claim',
    searchVolume: 14000,
    tier: 2,
    publishWeek: 5,
    relatedCalculator: '/',
    imagePrompt: 'Indian government housing scheme illustration with a modest family home, subsidy benefit visual, saffron white green palette, national housing scheme feel, no faces, no text, clean vector',
    publishedAt: '2025-04-29',
  },
  {
    slug: 'home-loan-tax-benefit-80c-24b-2025',
    title: 'Home Loan Tax Benefits 2025: What You Can Actually Claim Under 80C and 24(b)',
    description: 'The home loan tax deduction system is misunderstood by most borrowers. We explain exactly what you can claim, what you cannot, and how old vs new regime changes everything.',
    category: 'Tax Planning',
    tags: ['80C', '24b', 'tax benefit', 'home loan', 'income tax', '2025'],
    seoKeyword: 'home loan tax benefit 80C 24b 2025 India',
    searchVolume: 22000,
    tier: 2,
    publishWeek: 5,
    featured: true,
    relatedCalculator: '/calculators/tax-benefit',
    imagePrompt: 'Clean illustration of Indian income tax concept — a house icon with deduction arrows pointing away from it, professional government tax document aesthetic, blue and white, simplified, no text, no faces',
    publishedAt: '2025-04-30',
  },
  {
    slug: 'old-vs-new-tax-regime-home-loan',
    title: 'Old Tax Regime vs New Tax Regime: Which is Better if You Have a Home Loan?',
    description: 'The new regime has lower rates but removes home loan deductions. For most home loan borrowers in the 30% slab, the old regime wins by ₹60,000+ per year. We show exactly when that changes.',
    category: 'Tax Planning',
    tags: ['old regime', 'new regime', 'home loan', 'tax planning', '80C', '24b'],
    seoKeyword: 'old vs new tax regime home loan which better India',
    searchVolume: 15000,
    tier: 2,
    publishWeek: 6,
    relatedCalculator: '/calculators/tax-benefit',
    imagePrompt: 'Side-by-side comparison visual of two tax regimes, balance scale or split-path metaphor, professional Indian tax context, blue and green split palette, no text, no faces, clean infographic',
    publishedAt: '2025-05-05',
  },
  {
    slug: 'debt-free-date-calculator',
    title: 'When Will You Pay Your Last EMI? Calculate Your Exact Debt-Free Date',
    description: 'Most home loan borrowers have no idea when their loan actually ends. Your bank statement shows the tenure, but part payments and rate changes shift it constantly. Here is how to find your real debt-free date.',
    category: 'EMI Management',
    tags: ['debt free date', 'last EMI', 'home loan', 'calculator', 'tenure'],
    seoKeyword: 'when will I pay my last EMI home loan India calculator',
    searchVolume: 2500,
    tier: 2,
    publishWeek: 6,
    relatedCalculator: '/dashboard',
    imagePrompt: 'Calendar with a highlighted future date marked as debt-free, countdown visual concept, hopeful and aspirational feel, green and white, no text, no faces, clean modern vector',
    publishedAt: '2025-05-06',
  },
  {
    slug: 'home-loan-balance-transfer-step-by-step',
    title: 'Home Loan Balance Transfer: The Step-by-Step Process in India',
    description: 'Decided to transfer your home loan to a lower rate? Here is the exact process, every document you need, every fee to watch out for, and the timeline from application to disbursement.',
    category: 'Home Loans',
    tags: ['balance transfer', 'home loan', 'process', 'documents', 'step by step'],
    seoKeyword: 'home loan balance transfer process India step by step',
    searchVolume: 6000,
    tier: 2,
    publishWeek: 6,
    relatedCalculator: '/calculators/balance-transfer',
    imagePrompt: 'Step-by-step process illustration showing bank transfer stages as connected nodes or a flowchart, clean process diagram style, teal and white, no text, professional fintech',
    publishedAt: '2025-05-07',
  },
  {
    slug: 'personal-loan-vs-home-loan-top-up',
    title: 'Personal Loan vs Home Loan Top-Up: Which Is Cheaper for Emergency Funds?',
    description: 'When you need ₹5-10L quickly, a home loan top-up is almost always cheaper than a personal loan. But there are three situations where a personal loan wins. We show the exact numbers.',
    category: 'Personal Loans',
    tags: ['personal loan', 'home loan top up', 'emergency fund', 'interest rate', 'comparison'],
    seoKeyword: 'personal loan vs home loan top up which is cheaper India',
    searchVolume: 4500,
    tier: 2,
    publishWeek: 7,
    relatedCalculator: '/',
    imagePrompt: 'Split comparison of two loan types with interest rate indicators, one clearly lower than the other, simple cost comparison visual, blue and orange palette, no text, no faces, clean infographic',
    publishedAt: '2025-05-12',
  },
  {
    slug: 'what-is-rllr-home-loan-india',
    title: 'What Is RLLR and How Does It Actually Affect Your Home Loan EMI?',
    description: 'Your home loan agreement mentions RLLR and you have no idea what it is or how it changes your EMI. RLLR is the Repo Rate Linked Lending Rate — here is exactly what it means for you.',
    category: 'Home Loans',
    tags: ['RLLR', 'repo rate', 'home loan', 'EMI', 'lending rate', 'RBI'],
    seoKeyword: 'what is RLLR home loan India how it affects EMI',
    searchVolume: 3500,
    tier: 2,
    publishWeek: 7,
    relatedCalculator: '/',
    imagePrompt: 'Illustration of an interconnected chain showing RBI repo rate linking to bank lending rate to home loan EMI, simple mechanism diagram, professional financial infographic, blue and teal, no text',
    publishedAt: '2025-05-13',
  },
  {
    slug: 'negotiate-lower-interest-rate-bank',
    title: 'How to Negotiate a Lower Interest Rate on Your Existing Home Loan',
    description: 'Banks lower rates for new customers but not existing ones unless you ask. Here is the exact script to use, what data to bring to the conversation, and what threats actually work.',
    category: 'Home Loans',
    tags: ['negotiate', 'interest rate', 'home loan', 'bank', 'lower rate'],
    seoKeyword: 'how to negotiate lower interest rate existing home loan India',
    searchVolume: 4000,
    tier: 2,
    publishWeek: 7,
    relatedCalculator: '/',
    imagePrompt: 'Illustration of a person (shown only as silhouette or abstract figure) negotiating at a bank counter with a downward arrow on an interest rate display, confident negotiation concept, blue and white, no faces, professional',
    publishedAt: '2025-05-14',
  },
  {
    slug: 'step-up-emi-should-you-increase-emi-every-year',
    title: 'Step-Up EMI: Should You Increase Your Home Loan EMI Every Year?',
    description: 'If your salary increases 10% every year, should your EMI increase too? Step-up EMI can cut 5-7 years off a 20-year loan. But it only makes sense in specific situations. Here is the calculation.',
    category: 'EMI Management',
    tags: ['step up EMI', 'EMI increase', 'home loan', 'salary hike', 'prepayment'],
    seoKeyword: 'step up EMI home loan India should you increase EMI every year',
    searchVolume: 2000,
    tier: 2,
    publishWeek: 8,
    relatedCalculator: '/',
    imagePrompt: 'Staircase illustration showing EMI payments growing year by year with the loan balance reducing faster, upward steps concept for EMI growth, financial progress visual, blue and green, no text, clean vector',
    publishedAt: '2025-05-19',
  },
  {
    slug: 'home-loan-foreclosure-vs-part-payment',
    title: 'Home Loan Foreclosure vs Part Payment: Which Should You Do First?',
    description: 'You have a large lump sum. Should you foreclose the loan entirely or make a series of part payments? The answer depends on how much you have and where you are in the tenure.',
    category: 'Part Payments',
    tags: ['foreclosure', 'part payment', 'home loan', 'lump sum', 'prepayment'],
    seoKeyword: 'home loan foreclosure vs part payment which first India',
    searchVolume: 3000,
    tier: 2,
    publishWeek: 8,
    relatedCalculator: '/',
    imagePrompt: 'Two-path decision illustration showing a full loan closure on one path versus staged part payments on the other, decision crossroads concept, blue and teal, no text, clean professional financial vector',
    publishedAt: '2025-05-20',
  },
  {
    slug: 'credit-score-impact-part-payments',
    title: 'Credit Score Impact of Home Loan Part Payments: What Banks Do Not Tell You',
    description: 'Making part payments on your home loan affects your credit score in ways most borrowers do not expect. Some effects are positive. Some are not. Here is exactly what CIBIL sees.',
    category: 'Part Payments',
    tags: ['credit score', 'CIBIL', 'part payment', 'home loan', 'credit impact'],
    seoKeyword: 'credit score impact home loan part payment CIBIL India',
    searchVolume: 2500,
    tier: 2,
    publishWeek: 8,
    relatedCalculator: '/',
    imagePrompt: 'Credit score dial or gauge with an upward trend arrow, home loan document in background, professional fintech visual, blue and green, no faces, no text, clean vector',
    publishedAt: '2025-05-21',
  },

  // ═══════════════════════════════════════
  // TIER 3 — Weeks 9-12 (topical authority)
  // ═══════════════════════════════════════
  {
    slug: 'joint-home-loan-tax-benefits',
    title: 'Joint Home Loan Tax Benefits: How to Double Your Deductions Legally',
    description: 'A joint home loan with your spouse can double your 80C and 24(b) deductions to ₹7 lakh per year. But only if you structure it correctly. Here is exactly how it works.',
    category: 'Tax Planning',
    tags: ['joint home loan', 'tax benefit', '80C', '24b', 'double deduction', 'spouse'],
    seoKeyword: 'joint home loan tax benefit 80C 24b double deduction India',
    searchVolume: 4500,
    tier: 3,
    publishWeek: 9,
    relatedCalculator: '/calculators/tax-benefit',
    imagePrompt: 'Two connected home ownership documents representing joint ownership, with tax deduction arrows flowing from both, partnership concept for home loans, blue and green, no faces, no text, clean professional',
    publishedAt: '2025-05-26',
  },
  {
    slug: 'home-loan-insurance-worth-it',
    title: 'Home Loan Insurance: Is It Worth It or Is It a Waste of ₹2-3 Lakh?',
    description: 'Banks push home loan insurance aggressively. It costs ₹2-3 lakh upfront on a ₹50L loan. We analyse when it is worth it, when it is not, and what to do instead.',
    category: 'Home Loans',
    tags: ['home loan insurance', 'HLPP', 'insurance', 'cost analysis', 'home loan'],
    seoKeyword: 'home loan insurance worth it India should you buy',
    searchVolume: 5500,
    tier: 3,
    publishWeek: 9,
    relatedCalculator: '/',
    imagePrompt: 'Home with a protective shield concept, insurance and protection visual for home loan, professional fintech illustration, blue and white, no text, no faces, clean vector',
    publishedAt: '2025-05-27',
  },
  {
    slug: 'sbi-hdfc-icici-home-loan-rate-comparison-2025',
    title: 'SBI vs HDFC vs ICICI Home Loan: Honest Interest Rate Comparison 2025',
    description: 'Bank websites show you their best rates. We show you what most borrowers actually get, what fees are hidden, and which bank genuinely wins for different borrower profiles.',
    category: 'Home Loans',
    tags: ['SBI', 'HDFC', 'ICICI', 'home loan', 'interest rate', 'comparison', '2025'],
    seoKeyword: 'SBI HDFC ICICI home loan interest rate comparison 2025',
    searchVolume: 8000,
    tier: 3,
    publishWeek: 9,
    relatedCalculator: '/calculators/home-loan-eligibility',
    imagePrompt: 'Three bank building silhouettes side by side with interest rate comparison bars below them, honest comparison visual, blue and white, no logos or text, clean professional financial infographic',
    publishedAt: '2025-05-28',
  },
  {
    slug: 'loan-against-property-vs-personal-loan',
    title: 'Loan Against Property vs Personal Loan: The Real Cost Comparison',
    description: 'LAP offers lower rates but risks your home. A personal loan costs more but has no collateral risk. We run the complete comparison for ₹10L over 5 years including all hidden fees.',
    category: 'Personal Loans',
    tags: ['loan against property', 'personal loan', 'LAP', 'comparison', 'collateral'],
    seoKeyword: 'loan against property vs personal loan India comparison',
    searchVolume: 6000,
    tier: 3,
    publishWeek: 10,
    relatedCalculator: '/',
    imagePrompt: 'Comparison illustration of a home as collateral on one side and a clean personal document on the other, risk vs cost comparison visual, blue and orange balanced, no text, no faces, professional',
    publishedAt: '2025-06-02',
  },
  {
    slug: 'home-loan-prepayment-penalty-rules',
    title: 'Home Loan Prepayment Penalty: When Can Banks Charge You and When Can They Not?',
    description: 'Fixed rate loan? You may owe a penalty. Floating rate? By RBI rule, zero penalty. But the boundary between fixed and floating is blurry. Here is exactly when you are protected.',
    category: 'Home Loans',
    tags: ['prepayment penalty', 'fixed rate', 'floating rate', 'RBI rule', 'home loan'],
    seoKeyword: 'home loan prepayment penalty rules India when can bank charge',
    searchVolume: 3500,
    tier: 3,
    publishWeek: 10,
    relatedCalculator: '/',
    imagePrompt: 'Scale of justice illustration with a bank on one side and a borrower on the other, RBI shield protecting the borrower side, regulatory fairness concept, blue and saffron, no text, no faces, clean vector',
    publishedAt: '2025-06-03',
  },
  {
    slug: 'how-inflation-affects-real-emi-burden',
    title: 'How Inflation Makes Your Home Loan EMI Cheaper Over Time (And How to Use This)',
    description: 'Your EMI stays the same for 20 years. But inflation makes your salary go up. So in real terms, your EMI burden shrinks every year. Here is what this means for your prepayment strategy.',
    category: 'Debt Strategy',
    tags: ['inflation', 'EMI', 'real value', 'home loan', 'prepayment strategy'],
    seoKeyword: 'how inflation affects home loan EMI real burden India',
    searchVolume: 1500,
    tier: 3,
    publishWeek: 10,
    relatedCalculator: '/',
    imagePrompt: 'Timeline showing a fixed EMI bar with an inflation purchasing power chart growing over the same period, the EMI becoming relatively smaller over time, conceptual financial illustration, blue and green, no text, clean vector',
    publishedAt: '2025-06-04',
  },
  {
    slug: 'car-loan-prepayment-vs-home-loan',
    title: 'Car Loan vs Home Loan: Which Should You Prepay First?',
    description: 'If you have surplus money and both a car loan and a home loan, the math clearly says one of them should be paid off first. But the answer surprises most people.',
    category: 'Debt Strategy',
    tags: ['car loan', 'home loan', 'prepayment', 'priority', 'debt strategy'],
    seoKeyword: 'should I prepay car loan or home loan first India',
    searchVolume: 2500,
    tier: 3,
    publishWeek: 11,
    relatedCalculator: '/dashboard/planner',
    imagePrompt: 'Split illustration of a car on one side and a house on the other, with payment priority arrows pointing to one, decision-making financial concept, blue and orange, no text, no faces, clean vector',
    publishedAt: '2025-06-09',
  },
  {
    slug: 'credit-card-debt-vs-home-loan-part-payment',
    title: 'Pay Off Credit Card Debt First or Make Home Loan Part Payment?',
    description: 'Credit card debt at 36-42% or home loan at 8.5%? The math is obvious — but the execution requires a specific sequence. Here is the exact order of operations.',
    category: 'Debt Strategy',
    tags: ['credit card debt', 'home loan', 'prepayment', 'debt priority', 'interest rate'],
    seoKeyword: 'should I pay credit card debt or home loan prepayment India',
    searchVolume: 3000,
    tier: 3,
    publishWeek: 11,
    relatedCalculator: '/dashboard/planner',
    imagePrompt: 'Priority queue visual showing high-interest debt at the front with a home loan behind it, smart debt payoff order concept, red and blue palette showing urgency vs stability, no text, clean vector',
    publishedAt: '2025-06-10',
  },
  {
    slug: 'home-loan-noc-how-to-get',
    title: 'Home Loan NOC: How to Get It After Full Repayment and Why It Matters',
    description: 'After your last EMI, your loan is not truly closed until you have the NOC. Many borrowers skip this step and face problems years later. Here is exactly what to do.',
    category: 'Home Loans',
    tags: ['NOC', 'home loan', 'loan closure', 'repayment', 'property documents'],
    seoKeyword: 'home loan NOC how to get after repayment India',
    searchVolume: 4000,
    tier: 3,
    publishWeek: 11,
    relatedCalculator: '/',
    imagePrompt: 'Official document with a checkmark and a house key, loan closure completion concept, celebration of debt freedom, green and white, no text, no faces, clean professional fintech illustration',
    publishedAt: '2025-06-11',
  },
  {
    slug: 'debt-free-before-50-india',
    title: 'Debt-Free Before 50: A Realistic Plan for Indian Home Loan Borrowers',
    description: 'If you are 35 with a 20-year home loan, you will be 55 before your last EMI. Unless you have a plan. Here is a realistic, specific plan that can cut 5-8 years off that timeline.',
    category: 'Debt Strategy',
    tags: ['debt free', 'financial freedom', 'home loan', 'early payoff', 'plan'],
    seoKeyword: 'debt free before 50 India home loan plan',
    searchVolume: 2000,
    tier: 3,
    publishWeek: 12,
    relatedCalculator: '/dashboard/planner',
    imagePrompt: 'Road or path illustration leading to a milestone marker at age 50, debt-freedom journey concept, aspirational and hopeful, green and blue, no text, no faces, inspirational financial visual',
    publishedAt: '2025-06-16',
  },
  {
    slug: 'what-happens-emi-rbi-repo-rate-increase',
    title: 'What Happens to Your Home Loan EMI When RBI Increases the Repo Rate?',
    description: 'When RBI raises the repo rate, your floating rate home loan changes. But exactly how much? And should you lock in a fixed rate? Here is the real impact with numbers.',
    category: 'EMI Management',
    tags: ['RBI', 'repo rate increase', 'EMI impact', 'floating rate', 'fixed rate'],
    seoKeyword: 'what happens EMI when RBI increases repo rate India',
    searchVolume: 5000,
    tier: 3,
    publishWeek: 12,
    relatedCalculator: '/rbi-rates',
    imagePrompt: 'Graph showing repo rate going up with a corresponding EMI increase bar below it, RBI monetary policy impact illustration, clean financial chart style, blue and orange, no text, professional',
    publishedAt: '2025-06-17',
  },
  {
    slug: 'lastemi-year-one-most-important-home-loan-decisions',
    title: 'The 7 Most Important Home Loan Decisions That Determine Your Total Interest Paid',
    description: 'Most borrowers make all 7 of these decisions based on gut feel. Making even 3 of them correctly can save ₹10-20 lakh in interest over a 20-year loan. Here is what they are.',
    category: 'Home Loans',
    tags: ['home loan decisions', 'interest savings', 'loan planning', 'financial decisions'],
    seoKeyword: 'most important home loan decisions total interest paid India',
    searchVolume: 1500,
    tier: 3,
    publishWeek: 12,
    relatedCalculator: '/',
    imagePrompt: 'Seven connected decision nodes in a flow diagram, each representing a key home loan choice, strategic decision-making visual, clean professional financial infographic, blue and white, no text, vector',
    publishedAt: '2025-06-18',
  },
]

// CLI helper
if (typeof require !== 'undefined' && require.main === module) {
  POSTS.forEach(p => console.log(`[T${p.tier} W${p.publishWeek}] ${p.slug}`))
}
