/**
 * PDF report generation using jsPDF.
 * Generates a loan portfolio summary PDF.
 */

import type { Loan, DashboardStats } from "@/types";

import { formatINR, formatLakhs, formatDate, formatMonths } from "./formatters";

export async function generatePortfolioPDF(
  loans: Loan[],
  stats: DashboardStats,
  userName: string,
): Promise<void> {
  const { default: jsPDF } = await import("jspdf");
  const { default: autoTable } = await import("jspdf-autotable");

  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Title
  doc.setFontSize(18);
  doc.setTextColor(31, 41, 55);
  doc.text("EMIPartPay — Loan Portfolio Report", pageWidth / 2, 20, {
    align: "center",
  });

  doc.setFontSize(10);
  doc.setTextColor(107, 114, 128);
  doc.text(
    `Generated for ${userName || "User"} on ${new Date().toLocaleDateString("en-IN")}`,
    pageWidth / 2,
    28,
    { align: "center" },
  );

  // Summary Stats
  doc.setFontSize(12);
  doc.setTextColor(31, 41, 55);
  doc.text("Portfolio Summary", 14, 42);

  autoTable(doc, {
    startY: 46,
    head: [["Metric", "Value"]],
    body: [
      ["Total Debt Outstanding", formatLakhs(stats.totalDebt)],
      ["Monthly EMI Burden", formatINR(stats.monthlyEmiTotal)],
      ["Total Interest Remaining", formatLakhs(stats.totalInterestRemaining)],
      [
        "Debt-Free Date",
        stats.debtFreeDate ? formatDate(stats.debtFreeDate) : "N/A",
      ],
      ["Active Loans", String(stats.loanCount)],
    ],
    theme: "grid",
    headStyles: { fillColor: [37, 99, 235] },
    styles: { fontSize: 9 },
  });

  // Loan Details Table
  const tableY = (doc as unknown as { lastAutoTable: { finalY: number } })
    .lastAutoTable.finalY + 12;

  doc.setFontSize(12);
  doc.text("Loan Details", 14, tableY);

  autoTable(doc, {
    startY: tableY + 4,
    head: [["Loan", "Lender", "Outstanding", "Rate", "EMI", "Tenure"]],
    body: loans
      .filter((l) => l.isActive)
      .map((l) => [
        l.name,
        l.lender || "—",
        formatLakhs(l.currentOutstanding),
        `${l.interestRate}%`,
        formatINR(l.emiAmount),
        formatMonths(l.tenureMonths),
      ]),
    theme: "grid",
    headStyles: { fillColor: [37, 99, 235] },
    styles: { fontSize: 8 },
    columnStyles: {
      2: { halign: "right" },
      3: { halign: "right" },
      4: { halign: "right" },
    },
  });

  // Footer
  const footerY = doc.internal.pageSize.getHeight() - 10;
  doc.setFontSize(8);
  doc.setTextColor(156, 163, 175);
  doc.text(
    "Generated by EMIPartPay — emipartpay.com",
    pageWidth / 2,
    footerY,
    { align: "center" },
  );

  doc.save("emipartpay-loan-report.pdf");
}
